### ISSUE TITLE
soundpool_windux is incompatible with soundpool_web due to http version dependency

### ISSUE THREAD

**Issue by calcitem** [ukasz123/soundpool#124]
Hello ukasz123,

I want to express my gratitude for creating the soundpool package, it has been very useful to [my Flutter project](https://github.com/calcitem/Sanmill/blob/master/src/ui/flutter_app/pubspec.yaml) which I plan to deploy on Android, iOS, Windows, and Linux platforms.

Here is a section of my pubspec.yaml:

```yaml
soundpool: 2.4.1
soundpool_windux:
   git:
      url: git@github.com:ukasz123/soundpool.git
      ref: windows_linux_support
      path: soundpool_windux
```

Unfortunately, I encounter an error when I run `flutter pub get`:

```bash
$ flutter pub get
Resolving dependencies...
Because every version of soundpool_windux from git depends on http ^0.13.3 and soundpool_web >=2.3.0 depends on http ^1.1.0, soundpool_windux from git is incompatible with soundpool_web >=2.3.0.
And because soundpool >=2.4.0 depends on soundpool_web ^2.3.0, soundpool_windux from git is incompatible with soundpool >=2.4.0.
So, because sanmill depends on both soundpool 2.4.1 and soundpool_windux from git, version solving failed.
```

It would be great if you could rebase the `windows_linux_support` branch to the latest.

Currently, I am maintaining my own version:

```yaml
soundpool:
   git:
      url: https://gitlab.com/calcitem/soundpool.git
      ref: master
      path: soundpool
soundpool_windux:
   git:
      url: https://gitlab.com/calcitem/soundpool.git
      ref: windows_linux_support
      path: soundpool_windux
```

However, this approach has its own inconveniences. I am hoping that you can assist with this issue.

Best regards,
Calcitem
