### ISSUE TITLE
[Feature request] Desktop like Linux/Windows support?

### ISSUE THREAD

**Issue by liudonghua123** [ukasz123/soundpool#46]
I saw this package support android/ios/macos, and it seems lack of support for Linux/Windows desktop platform. Is there any plans or schedules for support them?

**Comment by ukasz123** [comment]
Unfortunately I have no plans for adding Linux/Windows support. It would require me spending some time learning how to implement native part of this plugin and I have not much time to spend at the moment.

**Comment by ukasz123** [comment]
I am trying to implement the feature using Rust through FFI and [rodio](https://docs.rs/rodio/0.14.0/rodio/index.html) crate.
Still, help is surely needed.

**Comment by ukasz123** [comment]
I prepared native implementation that uses rodio on `windows_linux_support` [branch](https://github.com/ukasz123/soundpool/tree/windows_linux_support/soundpool_windux). This is an experimental implementation and may cause issues (may even not compile on some environments).
It is compatible with `soundpool_platform_interface` 2.1.0.
To add dependency add following code in _pubspec.yaml_:
```
dependencies:
  soundpool_windux:
    git:
      url: https://github.com/ukasz123/soundpool.git
      ref: windows_linux_support
      path: soundpool_windux
```
