### ISSUE TITLE
Presence of android/ directory breaks Android builds on Flutter 2.10

### ISSUE THREAD

**Issue by stuartmorgan** [ukasz123/soundpool#92]
See https://github.com/flutter/flutter/issues/97729

1. Make a new Flutter application project with 2.10
2. Add `soundpool` to it
3. Try to build the app for Android

While this is a bug in Flutter, and will be fixed there, you can fix this in the plugin simply by removing the unused `android/` folder from your macOS and web implementation packages; see https://github.com/flutter/flutter/issues/97729#issuecomment-1030139198

**Comment by YDA93** [comment]
I have removed the android folder from macOS and Web and yet the error persists.

for your kind feedback ;(

https://github.com/YDA93/soundpool.git

**Comment by stuartmorgan** [comment]
> I have removed the android folder from macOS and Web and yet the error persists.

I don't see any build errors when using your versions of those packages, so you'll need to be more specific about what exactly your test setup was.

**Comment by YDA93** [comment]
Steps to reproduce:

1. Add forked soundpool to pubspec yaml 
```
  soundpool:
    git:
      url: https://github.com/YDA93/soundpool.git
      path: soundpool/
```

2. run the app

Result:
```
Plugin project :soundpool_web not found. Please update settings.gradle.
Plugin project :soundpool_macos not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* Where:
Script '[/Users/yousefalmutairi/flutter/packages/flutter_tools/gradle/flutter.gradle]()' line: 421

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot invoke method afterEvaluate() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 2s
```

**Comment by YDA93** [comment]
@stuartmorgan I noticed the android folders are automatically added after I pub get. Even after removing them from codebase.

**Comment by alexobviously** [comment]
+1, this is also killing my builds

**Comment by YDA93** [comment]
Ok now I finally fixed it by changing the pubspec to 
```
  soundpool_web:
    path: /Users/yousefalmutairi/Desktop/soundpool/soundpool_web
  soundpool_macos:
    path: /Users/yousefalmutairi/Desktop/soundpool/soundpool_macos
```

Because the old one is referencing the one on pub.dev

Guess we need to wait for pr https://github.com/ukasz123/soundpool/pull/94 to be accepted and updated in pub.dev

Thanks!

**Comment by stuartmorgan** [comment]
You don't need to use local references to use your forked version, you can use `dependency_overrides`:

```
dependency_overrides:
  soundpool_macos:
    git:
      url: https://github.com/YDA93/soundpool.git
      path: soundpool_macos
  soundpool_web:
    git:
      url: https://github.com/YDA93/soundpool.git
      path: soundpool_web
```
